services:
  dev-db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskGhar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskghar

volumes:
  postgres_data:

networks:
  taskghar:
